### ISSUE TITLE
Ability to reorder bookmarks, to-dos, and notes

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/tab#167]
Drag-and-drop reordering. Probably have an "edit mode" toggle that allows reordering and deletion.

**Comment by Countryen** [comment]
Hey devs, could you add the same for the ads on the (now) bottom right corner?

**Comment by kmjennison** [comment]
@Countryen What would be your ideal ad positions? As they are now but mirrored to the left side of the page?

**Comment by Countryen** [comment]
@kmjennison I'd like to move them on my own (drag and drop) or at least the possibility to switch them freely from left to right to bottom to top. Reason: I use nice backround pictures that have little things I like to see. Sometimes these are on the left, sometimes on the right / top / bottom.

Having the option would allow for more pictures to chose (right now, I only use pictures w/o something on the left side).

It the option is not possible, the right side (as it is now) will probably be the best.

**Comment by kmjennison** [comment]
@Countryen Thanks for sharing your thoughts! Opened an issue:
https://github.com/gladly-team/tab/issues/421

**Comment by WesleyM77** [comment]
Would love to be able to reorder the bookmarks. My list is getting kind of unwieldy and needs to be reordered. Would be cool if we could change how many can be in a row.

**Comment by kmjennison** [comment]
@WesleyM77 You can actually reorder bookmarks currently, though the process is a bit clunky. To reorder:
1. Click the lock icon in the bookmarks area
2. Click the "edit" icon on a particular bookmark
3. Click "move up" or "move down" and save

**Comment by kmjennison** [comment]
Closing here and migrating to product roadmap.
