### ISSUE TITLE
Keys and Secrets in .travis.yml

### ISSUE THREAD

**Issue by alexdriedger** [gladly-team/tab#180]
Currently `.travis.yml` is full of keys and secrets

This could very easily be a security risk. And even if isn't, those keys should be [environment variables](https://docs.travis-ci.com/user/environment-variables/)

**Comment by kmjennison** [comment]
Thanks for filing an issue. These are in fact env variable definitions [declared via travis.yml](https://docs.travis-ci.com/user/environment-variables/#Defining-public-variables-in-.travis.yml). Only non-sensitive variables are in plain text (e.g. the [`FIREBASE_API_KEY` is not sensitive](https://firebase.google.com/docs/web/setup)). All secrets are encrypted. 

If you do see any plain text sensitive env vars or any other urgent security risk, feel free to email me at kevin@gladly.io.
