### ISSUE TITLE
Usage of Tab with Amazon A9 

### ISSUE THREAD

**Issue by Engywook2005** [gladly-team/tab#706]
Toward the bottom of this thread on a prebid adapter for Amazon A9

https://github.com/prebid/Prebid.js/issues/393

@kmjennison notes that he now prefers to use https://github.com/gladly-team/tab/blob/master/web/src/js/ads/ads.js for that purpose.

Is this still the recommended way to approach A9? 

If so, I wonder if there's any documentation about how to implement as a library supporting another app. An example implementation would be particularly helpful.

In the meantime I shall see what I can figure out myself.

Thanks in advance for any help,

Greg T

**Comment by kmjennison** [comment]
Yes, that's how we're managing bidders who aren't part of Prebid for whatever reason. We basically wrote a small request manager, like a simple Prebid on top of Prebid and other adapters. It's worked reasonably well for us.
