### ISSUE TITLE
Chromium not supported?

### ISSUE THREAD

**Issue by dionysius** [gladly-team/tab#797]
I'm unable to use the plugin on my chromium at work. I had no issues at home on my chrome.

The error happens once I try to log in via google.
![image](https://user-images.githubusercontent.com/1341084/87534550-78111180-c696-11ea-82a0-a70c63a872ed.png)
> This browser is not supported or 3rd party cookies and data may be disabled.

Ad blockers are disabled for that page.

**Comment by kmjennison** [comment]
@dionysius Chromium is supported. Most likely the browser or an extension is blocking 3rd party cookies or data. Can you navigate to chrome://settings/content/cookies and make sure "Block third-party cookies" is not enabled?

https://gladly.zendesk.com/hc/en-us/articles/360002449152-I-get-a-sign-in-error-This-browser-is-not-supported-or-3rd-party-cookies-and-data-may-be-disabled-

**Comment by dionysius** [comment]
That's what it was. Thank you!
