### ISSUE TITLE
Error following Getting Started from README

### ISSUE THREAD

**Issue by jeffslofish** [gladly-team/tab#833]
At step 3 `yarn run start:newtab` in the Getting Started instructions, I got the following error:

```
[docker]   dynamodb_1  | Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/spi/ExtendedLogger : Unsupported major.minor version 52.0
[docker]   dynamodb_1  |        at java.lang.ClassLoader.defineClass1(Native Method)
[docker]   dynamodb_1  |        at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
[docker]   dynamodb_1  |        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[docker]   dynamodb_1  |        at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
[docker]   dynamodb_1  |        at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
[docker]   dynamodb_1  |        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[docker]   dynamodb_1  |        at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
[docker]   dynamodb_1  |        at java.security.AccessController.doPrivileged(Native Method)
[docker]   dynamodb_1  |        at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
[docker]   dynamodb_1  |        at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
[docker]   dynamodb_1  |        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
[docker]   dynamodb_1  |        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
[docker]   dynamodb_1  |        at com.amazonaws.services.dynamodbv2.local.shared.logging.LogManager.<clinit>(LogManager.java:28)
[docker]   dynamodb_1  |        at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<clinit>(DynamoDBProxyServer.java:36)
[docker]   dynamodb_1  |        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:120)
[docker]   dynamodb_1  |        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:116)
[docker]   dynamodb_1  |        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:71)
[docker]   tab_dynamodb_1 exited with code 1
```

I did some research and it turns out you can get this error when attempting to use Java 6 to run a jar build with a later version of Java.

Furthermore, I noticed that the Dockerfile at `dynamodb/Dockerfile` uses the default-jre for ubuntu:14.04, but it gets the latest version of dynamodb from https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz. I believe the default-jre for ubuntu:14.04 is Java 6, but the latest dynamodb uses a later version that is not compatible.

I tried building with older versions and found the latest working version to be https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_2019-02-07.tar.gz. When I run `yarn run start:newtab` with this version, I am able to continue and correctly see the tab page at http://localhost:3000/newtab.

I believe you may have not had this error because Docker caches the images, and since the Dockerfile hasn't changed, but the files that https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz point to change periodically, only people who have done a new docker build after a certain time would notice this issue.

I could open a pull request for the change I made, if you like, but I figured instead of using an old version of dynamodb, you might want to get it working with a newer version of ubuntu that has a default-jre that is compatible with the latest version of dynamodb.

**Comment by kmjennison** [comment]
Thanks! Yes, I haven't had to rebuild the image in a while, so I wouldn't have run into this problem. I agree that using the latest Ubuntu LTS version makes sense. PR welcome.
