### ISSUE TITLE
Have more than one widget active in tab

### ISSUE THREAD

**Issue by RicardoM17** [gladly-team/tab#845]
Currently I have been using the bookmarks widget, but when I click on the to-do list it "closes" the bookmarks. This is unnecessary as there is so much space for more than just one widget.

Apologies if this is already possible I didn't find this option.

**Comment by kmjennison** [comment]
Duplicate #169 

Thanks for this feedback! I agree, and we're hoping to make this possible in the near term.

**Comment by RicardoM17** [comment]
Hi @kmjennison , sorry for the duplicate. Perhaps I missed it considering it's quite old now. Fingers crossed that it gets here soon :crossed_fingers: 

Thanks for the feedback.
