### ISSUE TITLE
free harts glitch

### ISSUE THREAD

**Issue by VarshithSatti** [gladly-team/tab#872]
if you open a tab and wait 4 seconds and open another tab you can get the hearts. and you can automate that. here is the script:  

window.open("https://tab.gladly.io/newtab/");
setTimeout(function(){
    window.open("https://tab.gladly.io/newtab/");
}, 3000);
setTimeout(function(){
   window.open("https://tab.gladly.io/newtab/");
}, 7000);
setTimeout(function(){
    window.open("https://tab.gladly.io/newtab/");
}, 11000);
setTimeout(function(){
    // now just copy paste all the code and repeat (this could be repeated forever)
}, 14000);

**Comment by kmjennison** [comment]
Yes, this is expected. While we have some safeguards in place, we also ask that our users only open tabs as they normally do. Trying to automate the process is unsurprisingly not good for advertisers and will ultimately decrease how much our community can raise for good causes.
